<?php
/**
 * Created by PhpStorm.
 * User: fernandobritofl
 * Date: 4/22/15
 * Time: 10:34 PM

 削除処理

 */
 
namespace dogears\L5scaffold\Makes;

use Illuminate\Console\AppNamespaceDetectorTrait;
use Illuminate\Filesystem\Filesystem;
use dogears\L5scaffold\Commands\ScaffoldMakeCommand;
use dogears\L5scaffold\Stubs\StubController;
use dogears\L5scaffold\Traits\MakerTrait;
use dogears\L5scaffold\Traits\NameSolverTrait;
use dogears\L5scaffold\Traits\OutputTrait;

class DeleteAll
{
    use AppNamespaceDetectorTrait, MakerTrait,NameSolverTrait,OutputTrait;

    protected $files;
    protected $commandObj;

    public function __construct($command, Filesystem $files)
    {
        $this->files = $files;
        $this->commandObj = $command;
        $this->start();
    }

    private function start()
    {
        //app_model_class
        $this->app_model_class = $this->solveName($this->commandObj->argument('name'),config('l5scaffold.app_name_rules.app_model_class'));

        $this->deleteFactory();
        $this->deleteDatabaseSeeder();
        $this->deleteSeed();
        $this->deleteModel();
        $this->deleteController();
        $this->deleteViews();
        $this->deleteViewLayoutNavi();
        $this->deleteRoute();
        $this->deleteRouteServiceProvider();

        $this->commandObj->info('Delete is done.');
        $this->commandObj->info('Rollback migration and delete migrate file if you need.');
    }

    private function deleteFactory(){

        $output_path = './database/factories/';
        $output_filename = 'ModelFactory.php';

        //replace word
        $pattern = '{\n\n// generated by scaffold - '.$this->app_model_class.' - start(.*?)// end}s';
        $replacement = "";
        
        //output(use OutputTrait)
        $this->outputReplace( $output_path, $output_filename, $pattern, $replacement, $message_success='Seeding - DatabaseSeeder updated successfully', $debug=false );
    }

    private function deleteDatabaseSeeder(){

        $output_path = './database/seeds/';
        $output_filename = 'DatabaseSeeder.php';

        //replace word
        $pattern = '{(.*?)//generated by scaffold - '.$this->app_model_class.'\n}';
        $replacement = "";
        
        //output(use OutputTrait)
        $this->outputReplace( $output_path, $output_filename, $pattern, $replacement, $message_success='remove generated data from DatabaseSeeder', $debug=false );
    }

    private function deleteSeed(){

        $output_path = './database/seeds/';
        $output_filename = $this->solveName($this->commandObj->argument('name'), config('l5scaffold.app_name_rules.app_seeder_class')).'TableSeeder.php';

        //output(use OutputTrait)
        $this->outputDelete( $output_path, $output_filename, $message_success = 'Seeding is Deleted', $debug=false );
    }

    private function deleteModel(){

        $output_path = './app/';
        $output_filename = $this->solveName($this->commandObj->argument('name'), config('l5scaffold.app_name_rules.app_model_class')).'.php';

        //output(use OutputTrait)
        $this->outputDelete( $output_path, $output_filename, $message_success = 'Model is Deleted', $debug=false );
    }

    private function deleteController(){
        //Controller -------------------- 
        $output_path = './app/Http/Controllers/';
        $output_filename = $this->solveName($this->commandObj->argument('name'), config('l5scaffold.app_name_rules.app_controller_class')).'Controller.php';

        //output(use OutputTrait)
        $this->outputDelete( $output_path, $output_filename, $message_success = 'Controller is Deleted', $debug=false );
    }

    private function deleteViews(){

        // Get path
        $output_path = './resources/views/'.$this->solveName($this->commandObj->argument('name'), config('l5scaffold.app_name_rules.app_route'));

        //output(use OutputTrait)
        $this->outputDeleteDirectory( $output_path, $message_success = 'View is Deleted', $debug=false );
    }

    private function deleteViewLayoutNavi(){

        $output_path = './resources/views/';
        $output_filename = 'navi.blade.php';

        //replace word
        $pattern = '#(.*?){{-- generated by scaffold - '.$this->app_model_class.' --}}\n#';
        $replacement = "";

        //output(use OutputTrait)
        $this->outputReplace( $output_path, $output_filename, $pattern, $replacement, $message_success='remove generated data from DatabaseSeeder', $debug=false );
    }

    private function deleteRoute(){
        //Route --------------------
        $output_path = './app/Http/';
        $output_filename = 'routes.php';

        //replace word
        $pattern = '{(.*?)//generated by scaffold - '.$this->app_model_class.'\n}';
        $replacement = "";

        //output(use OutputTrait)
        $this->outputReplace( $output_path, $output_filename, $pattern, $replacement, $message_success='remove generated data from Route', $debug=false );
    }

    private function deleteRouteServiceProvider(){

        $output_path = './app/Providers/';
        $output_filename = 'RouteServiceProvider.php';

        //replace word
        $pattern = '{(.*?)//generated by scaffold - '.$this->app_model_class.'\n}';
        $replacement = "";

        //output(use OutputTrait)
        $this->outputReplace( $output_path, $output_filename, $pattern, $replacement, $message_success='remove generated data from RouteServiceProvider', $debug=false );
    }
}