<?php

/**
Copyright (c) 2016 dog-ears

This software is released under the MIT License.
http://dog-ears.net/
*/
 
namespace dogears\CrudDscaffold\Makes;

use Illuminate\Console\DetectsApplicationNamespace;
use Illuminate\Filesystem\Filesystem;
use dogears\CrudDscaffold\Commands\ScaffoldMakeCommand;
use dogears\CrudDscaffold\Stubs\StubController;
use dogears\CrudDscaffold\Traits\MakerTrait;
use dogears\CrudDscaffold\Traits\NameSolverTrait;
use dogears\CrudDscaffold\Traits\OutputTrait;

class DeleteAll
{
    use DetectsApplicationNamespace, MakerTrait,NameSolverTrait,OutputTrait;

    protected $files;
    protected $commandObj;

    public function __construct($command, Filesystem $files)
    {
        $this->files = $files;
        $this->commandObj = $command;
        $this->start();
    }

    private function start()
    {
        //app_model_class
        $this->app_model_class = $this->solveName($this->commandObj->argument('name'),config('CrudDscaffold.app_name_rules.app_model_class'));

        //check seeding file exist
        $output_path = './database/seeds/';
        $output_filename = $this->solveName($this->commandObj->argument('name'), config('CrudDscaffold.app_name_rules.app_seeder_class')).'TableSeeder.php';

        if( $this->files->exists( $output_path. $output_filename ) ){
            $this->deleteFactory();
            $this->deleteDatabaseSeeder();
            $this->deleteSeed();
        }else{
            $this->commandObj->info('no seeding file.');
        }

        $this->deleteModel();
        $this->deleteController();
        $this->deleteViews();
        $this->deleteViewLayoutNavi();
        $this->deleteRouteForWeb();
        $this->deleteRouteForApi();
        $this->deleteRouteServiceProvider();
    }

    private function deleteFactory(){

        $output_path = './database/factories/';
        $output_filename = 'ModelFactory.php';

        //replace word
        $pattern = '#\n\n[ \r\t\f]*// generated by scaffold - '. $this->app_model_class. ' - start(.*?)// end#s';     //Delete block generated by scaffold
        $replacement = '';
        
        //output(use OutputTrait)
        $this->outputReplace( $output_path, $output_filename, $pattern, $replacement, $debug=false );
    }

    private function deleteDatabaseSeeder(){

        $output_path = './database/seeds/';
        $output_filename = 'DatabaseSeeder.php';

        //replace word
        $pattern = '#^.*?// generated by scaffold - '.$this->app_model_class.'\n#m';     //Delete 1 line generated by scaffold
        $replacement = '';
        
        //output(use OutputTrait)
        $this->outputReplace( $output_path, $output_filename, $pattern, $replacement, $debug=false );
    }

    private function deleteSeed(){

        $output_path = './database/seeds/';
        $output_filename = $this->solveName($this->commandObj->argument('name'), config('CrudDscaffold.app_name_rules.app_seeder_class')).'TableSeeder.php';

        //output(use OutputTrait)
        $this->outputDelete( $output_path, $output_filename, $debug=false );
    }

    private function deleteModel(){

        $output_path = './app/';
        $output_filename = $this->solveName($this->commandObj->argument('name'), config('CrudDscaffold.app_name_rules.app_model_class')).'.php';

        //output(use OutputTrait)
        $this->outputDelete( $output_path, $output_filename, $debug=false );
    }

    private function deleteController(){
        //Controller -------------------- 
        $output_path = './app/Http/Controllers/';
        $output_filename = $this->solveName($this->commandObj->argument('name'), config('CrudDscaffold.app_name_rules.app_controller_class')).'Controller.php';

        //output(use OutputTrait)
        $this->outputDelete( $output_path, $output_filename, $debug=false );
    }

    private function deleteViews(){

        // Get path
        $output_path = './resources/views/'.$this->solveName($this->commandObj->argument('name'), config('CrudDscaffold.app_name_rules.app_route'));

        //output(use OutputTrait)
        $this->outputDeleteDirectory( $output_path, $debug=false );
    }

    private function deleteViewLayoutNavi(){

        $output_path = './resources/views/';
        $output_filename = 'navi.blade.php';

        //replace word
        $pattern = '#^.*?{{-- generated by scaffold - '.$this->app_model_class.' --}}\n#m';
        $replacement = '';

        //output(use OutputTrait)
        $this->outputReplace( $output_path, $output_filename, $pattern, $replacement, $debug=false );
    }

    private function deleteRouteForWeb(){
        //Route --------------------
        $output_path = './routes/';
        $output_filename = 'web.php';

        //replace word
        $pattern = '#^.*?// generated by scaffold - '.$this->app_model_class.'\n#m';     //Delete 1 line generated by scaffold
        $replacement = '';

        //output(use OutputTrait)
        $this->outputReplace( $output_path, $output_filename, $pattern, $replacement, $debug=false );
    }

    private function deleteRouteForApi(){
/*
        //Route --------------------
        $output_path = './app/Http/';
        $output_filename = 'routes.php';

        //replace word
        $pattern = '#^.*?// generated by scaffold - '.$this->app_model_class.'\n#m';     //Delete 1 line generated by scaffold
        $replacement = '';

        //output(use OutputTrait)
        $this->outputReplace( $output_path, $output_filename, $pattern, $replacement, $debug=false );
*/
    }

    private function deleteRouteServiceProvider(){

        $output_path = './app/Providers/';
        $output_filename = 'RouteServiceProvider.php';

        //replace word
        $pattern = '#^.*?// generated by scaffold - '.$this->app_model_class.'\n#m';     //Delete 1 line generated by scaffold
        $replacement = '';

        //output(use OutputTrait)
        $this->outputReplace( $output_path, $output_filename, $pattern, $replacement, $debug=false );
    }
}